---
- name: create openstack pool
  command: ceph osd pool create {{ item.name }} {{ item.pg_num }}
  with_items:
    - "{{ openstack_glance_pool }}"
    - "{{ openstack_cinder_pool }}"
    - "{{ openstack_nova_pool }}"
  changed_when: false
  failed_when: false

- name: import openstack keys
  command: ceph auth import -i /etc/ceph/ceph.client.openstack.keyring
  with_items: openstack_keys
  changed_when: false
  when: cephx
